# k8s/resource-limits.yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: routine-app
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "200m"
        memory: "256Mi"
      type: Container