name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup Node
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    # Backend deps
    - name: Install Backend Dependencies
      working-directory: backend
      run: npm install

    # Frontend deps
    - name: Install Frontend Dependencies
      working-directory: frontend
      run: npm install

    # Build frontend
    - name: Build Frontend
      working-directory: frontend
      run: npm run build

    # 🔐 Login Docker Hub
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 🐳 Build + Tag Backend
    - name: Build Backend Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/routine-backend:latest ./backend

    # 🐳 Build + Tag Frontend
    - name: Build Frontend Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/routine-frontend:latest ./frontend

    # 🚀 Push Backend
    - name: Push Backend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/routine-backend:latest

    # 🚀 Push Frontend
    - name: Push Frontend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/routine-frontend:latest